title: Gabriel's Blog
author: Gabriel Majeri
email: gabriel.majeri6@gmail.com
description: >
  Writing never really gets old
url: "https://blog.gabrielmajeri.ro"

# Show excerpts of blog posts on main page
show_excerpts: true
excerpt_separator: <!-- more -->

# Use Disqus for comments
disqus:
  shortname: blog-gabrielmajeri-ro

# Social media links
github_username: GabrielMajeri
linkedin_username: gabriel-majeri
twitter_username: gabrielmajeri

# Theme selection
theme: minima

plugins:
  # Automatically update a RSS feed
  - jekyll-feed
  # Automatically generate a sitemap
  - jekyll-sitemap
  # Automatically add SEO tags
  - jekyll-seo-tag
  # Automatically add `target="_blank"` to external links
  - jekyll-target-blank

# Use kramdown for Markdown processing
markdown: kramdown

# Enable LaTeX support for math formulas
kramdown:
  math_engine: mathjax
