title: Gabriel's Blog
author: Gabriel Majeri
email: gabriel.majeri6@gmail.com
description: >
  An intelligent monkey's collection of thoughts on the modern world.
url: "https://blog.gabrielmajeri.ro"

# Show excerpts of blog posts on main page
show_excerpts: true
excerpt_separator: <!-- more -->

# Use Disqus for comments
disqus:
  shortname: blog-gabrielmajeri-ro

# Social media links
github_username: GabrielMajeri
linkedin_username: gabriel-majeri
twitter_username: gabrielmajeri

# Theme selection
theme: minima

plugins:
  # Automatically update a RSS feed
  - jekyll-feed
  # Automatically generate a sitemap
  - jekyll-sitemap
