title: Gabriel's Blog
author: Gabriel Majeri
email: gabriel.majeri6@gmail.com
description: >
  An intelligent monkey's collection of thoughts on the modern world.

# Theme selection
theme: minima

# Social media links
github_username: GabrielMajeri
linkedin_username: gabriel-majeri
twitter_username: gabrielmajeri

# Show excerpts of blog posts on main page
show_excerpts: true
